/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
//import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import paypal.Datos;

/**
 *
 * @author Ioan Alexandru Stanica
 * @version 1.10 07/02/2023
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    private Datos datos;

    public FPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        bColor.setBorder(null);
        this.datos = new Datos();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                if (JOptionPane.showConfirmDialog(rootPane, "¿Desea salir de la aplicación?",
                        "Salir", JOptionPane.ERROR_MESSAGE) == JOptionPane.ERROR_MESSAGE) {
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bColor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        chRecordarContra = new javax.swing.JCheckBox();
        bRegistrar = new javax.swing.JButton();
        bInicioSesion = new javax.swing.JButton();
        tfContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        pFondo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bColor.setForeground(new java.awt.Color(255, 255, 255));
        bColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconBackground.png"))); // NOI18N
        bColor.setBorder(null);
        bColor.setOpaque(true);
        bColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bColorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Contraseña:");

        jLabel3.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N
        jLabel3.setText("Usuario:");

        tfUsuario.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N

        chRecordarContra.setBackground(new java.awt.Color(255, 255, 255));
        chRecordarContra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chRecordarContra.setText("Recordarme la contraseña");

        bRegistrar.setFont(new java.awt.Font("Arial Nova", 0, 24)); // NOI18N
        bRegistrar.setText("Registrar");
        bRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });

        bInicioSesion.setFont(new java.awt.Font("Arial Nova", 0, 24)); // NOI18N
        bInicioSesion.setText("Iniciar Sesión");
        bInicioSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicioSesionActionPerformed(evt);
            }
        });

        tfContraseña.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N

        javax.swing.GroupLayout pFondoLayout = new javax.swing.GroupLayout(pFondo);
        pFondo.setLayout(pFondoLayout);
        pFondoLayout.setHorizontalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bColor))
                    .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pFondoLayout.createSequentialGroup()
                                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pFondoLayout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pFondoLayout.createSequentialGroup()
                                            .addGap(284, 284, 284)
                                            .addComponent(chRecordarContra))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLayout.createSequentialGroup()
                                            .addGap(111, 111, 111)
                                            .addComponent(bInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(65, 65, 65)
                                            .addComponent(bRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(pFondoLayout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addComponent(jLabel2))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        pFondoLayout.setVerticalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chRecordarContra)
                .addGap(44, 44, 44)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(bColor)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cambiar el fondo. Este boton permite cambiar el fondo de color.
     *
     * @param evt
     * @return true: <true>Si esta selecionado</true><br>
     * false: <false> Si no esta seleccionado</false>
     */
    private void bColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bColorActionPerformed

        if (bColor.isSelected()) {
            pFondo.setBackground(new Color(123, 215, 246));
            bColor.setBackground(new Color(123, 215, 246));
            tfUsuario.setBackground(new Color(123, 215, 246));
            tfContraseña.setBackground(new Color(123, 215, 246));
            chRecordarContra.setBackground(new Color(123, 215, 246));
            bInicioSesion.setBackground(new Color(123, 215, 246));
            bRegistrar.setBackground(new Color(123, 215, 246));
            bColor.setSelected(false);
        } else {
            pFondo.setBackground(Color.WHITE);
            bColor.setBackground(Color.WHITE);
            tfUsuario.setBackground(Color.WHITE);
            tfContraseña.setBackground(Color.WHITE);
            chRecordarContra.setBackground(Color.WHITE);
            bColor.setSelected(true);
        }

    }//GEN-LAST:event_bColorActionPerformed

    /**
     * Iniciar Sesión. Este boton permite acceder a otra aplicación si cumple
     * con alguna restricciones.
     *
     * @param evt
     * @return true: <true>Si es la misma contraseña y usuario</true><br>
     * false: <false> Si no es la misma contraseña y usuario</false>
     */
    private void bInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicioSesionActionPerformed

        datos.setUsuario("Alex");
        datos.setContraseña("as");
        if (tfUsuario.getText().equals("") && getContraseña().equals("")) {
            JOptionPane.showMessageDialog(null, "El usuario es: Alex\nLa contraseña es: as");
        } else if (datos.compararDatos(tfUsuario.getText(), getContraseña())) {
            JOptionPane.showMessageDialog(null, "Acceso Correcto");
            FEntrada entrada = new FEntrada();
            entrada.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Acceso Incorrecto");
        }
    }//GEN-LAST:event_bInicioSesionActionPerformed

    /**
     *
     * @param evt
     */
    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed

        FRegistrar v = new FRegistrar();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    /**
     * Icono.
     * Permite introducir un icono a la ventana
     * @return Devuelve una imagen de icono
     * @see img.iconPayPal.png# Imagen
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("img/iconPayPal.png"));
        return retValue;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bColor;
    private javax.swing.JButton bInicioSesion;
    private javax.swing.JButton bRegistrar;
    private javax.swing.JCheckBox chRecordarContra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pFondo;
    private javax.swing.JPasswordField tfContraseña;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables

//    public void setOidor(ActionListener oidor) {
//        bInicioSesion.addActionListener(oidor);
//        bRegistrar.addActionListener(oidor);
//    }
    public String getContraseña() {
        char[] arrayC = tfContraseña.getPassword();
        String contra = new String(arrayC);
        return contra;
    }
}
