/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
//import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import paypal.Datos;

/**
 *
 * @author Ioan Alexandru Stanica
 * @version 1.10 07/02/2023
 */
public class FRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form FRegistrar
     */
    
    private Datos datos;

    public FRegistrar() {
        initComponents();
        setLocationRelativeTo(this);
        this.datos = new Datos();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                if (JOptionPane.showConfirmDialog(rootPane, "¿Desea salir de la aplicación?",
                        "Salir", JOptionPane.ERROR_MESSAGE) == JOptionPane.ERROR_MESSAGE) {
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        tfUsuario1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        rbHombre = new javax.swing.JRadioButton();
        rbOtro = new javax.swing.JRadioButton();
        rbMujer = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfContraseña = new javax.swing.JPasswordField();
        bCrearCuenta = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N
        jLabel3.setText("Apellido:");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N
        jLabel4.setText("Usuario:");
        jLabel4.setToolTipText("");

        tfApellido.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N

        tfUsuario1.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N
        jLabel5.setText("Nombre:");
        jLabel5.setToolTipText("");

        tfNombre.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N

        rbHombre.setBackground(new java.awt.Color(255, 255, 255));
        sexoGrupo.add(rbHombre);
        rbHombre.setText("Hombre");

        rbOtro.setBackground(new java.awt.Color(255, 255, 255));
        sexoGrupo.add(rbOtro);
        rbOtro.setText("Otro");

        rbMujer.setBackground(new java.awt.Color(255, 255, 255));
        sexoGrupo.add(rbMujer);
        rbMujer.setText("Mujer");

        jLabel6.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N
        jLabel6.setText("Sexo:");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N
        jLabel7.setText("Correo:");
        jLabel7.setToolTipText("");

        tfCorreo.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Contraseña:");

        tfContraseña.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N

        bCrearCuenta.setFont(new java.awt.Font("Arial Nova", 0, 24)); // NOI18N
        bCrearCuenta.setText("Crear la cuenta");
        bCrearCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearCuentaActionPerformed(evt);
            }
        });

        bCancelar.setFont(new java.awt.Font("Arial Nova", 0, 24)); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbHombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbMujer)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbOtro))
                                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25)))
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbHombre)
                    .addComponent(rbMujer)
                    .addComponent(rbOtro)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Activar el boton Crear Cuenta.<br>
     * Este botón sirve para crear una cuenta.<br>
     * (Hay algunas funciones que están obsoletos)
     * @param evt
     * @return Cierra la ventana<br>Abre la ventana FPrincipal<br>Y guarda los datos
     * 
     */
    private void bCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearCuentaActionPerformed

        boolean tieneAcceso = true;
        char[] arrayC = tfContraseña.getPassword();
        String contra = new String(arrayC);
        if (tfNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No has introducido el Nombre");
            tieneAcceso = false;
        } else if (tfApellido.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No has introducido el Apellido");
            tieneAcceso = false;
        } else if (tfCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No has introducido el Correo");
            tieneAcceso = false;
        } else if (tfUsuario1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No has introducido el Usuario");
            tieneAcceso = false;
        } else if (contra.equals("")) {
            JOptionPane.showMessageDialog(null, "No has introducido la Contraseña");
            tieneAcceso = false;
        } else if (rbHombre.isSelected() == false && rbMujer.isSelected() == false && rbOtro.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "No has seleccionado el sexo");
            tieneAcceso = false;
        }
        
        if (tieneAcceso) {
//            datos.guardarDatos(tfNombre.getText(), tfApellido.getText(), contra, tfCorreo.getText());
            JOptionPane.showMessageDialog(null, "Cuenta creado");
            FPrincipal ventana = new FPrincipal();
            ventana.setVisible(true);
            this.dispose();
//            datos.setContraseña(contra);
//            datos.setUsuario("Alex");
        }

    }//GEN-LAST:event_bCrearCuentaActionPerformed

    /**
     * Cancerlar Ventana.
     * Este boton permite cancerla la ventana.
     * @param evt 
     * @return Cierra la ventana y abre la ventana FPrincipal
     */
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Desea cancelar?",
                        "Cancelar", JOptionPane.ERROR_MESSAGE) == JOptionPane.ERROR_MESSAGE) {
                    FPrincipal ventana = new FPrincipal();
                    ventana.setVisible(true);
                    this.dispose();
                }
    }//GEN-LAST:event_bCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRegistrar().setVisible(true);
            }
        });
    }

    /**
     * Icono.
     * Permite introducir un icono a la ventana
     * @return Devuelve una imagen de icono
     * @see img.iconPayPal.png# Imagen
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("img/iconPayPal.png"));
        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bCrearCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.ButtonGroup sexoGrupo;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JPasswordField tfContraseña;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfUsuario1;
    // End of variables declaration//GEN-END:variables


//    public void setOidor(ActionListener oidor) {
//        bCancelar.addActionListener(oidor);
//        bCrearCuenta.addActionListener(oidor);
//    }
//
//    public boolean cumpleDatos() {
//        boolean tieneAcceso = true;
//        String contra = new String(tfContraseña.getPassword());
//        if (tfNombre.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "No has introducido el Nombre");
//            tieneAcceso = false;
//        } else if (tfApellido.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "No has introducido el Apellido");
//            tieneAcceso = false;
//        } else if (tfCorreo.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "No has introducido el Correo");
//            tieneAcceso = false;
//        } else if (tfUsuario1.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "No has introducido el Usuario");
//            tieneAcceso = false;
//        } else if (contra.equals("")) {
//            JOptionPane.showMessageDialog(null, "No has introducido la Contraseña");
//            tieneAcceso = false;
//        } else if (rbHombre.isSelected() == false && rbMujer.isSelected() == false && rbOtro.isSelected() == false) {
//            JOptionPane.showMessageDialog(null, "No has seleccionado el sexo");
//            tieneAcceso = false;
//        }
//        return tieneAcceso;
//    }
//
//    public String getUsuario() {
//        return tfUsuario1.getText();
//    }
//
//    public String getContraseña() {
//        char[] arrayC = tfContraseña.getPassword();
//        String contra = new String(arrayC);
//        return contra;
//    }
    
}
